rvm:
  - 2.1
  - 2.2.5
  - 2.3.1

gemfile:
  - gemfiles/4.2.gemfile
  - gemfiles/5.0.gemfile

before_install:
  - gem install bundler

matrix:
  exclude:
    - rvm: 2.1
      gemfile: gemfiles/5.0.gemfile

notifications:
  recipients:
    - weppos@weppos.net
